server:
  port: 8082

spring:
  application:
    name: dubbo-registry-nacos-provider-sample

nacos1:
  host: 127.0.0.1
  port: 8857
  username: nacos
  password: nacos
nacos2:
  host: 127.0.0.1
  port: 8858
  username: nacos
  password: nacos
nacos3:
  host: 127.0.0.1
  port: 8859
  username: nacos
  password: nacos

dubbo:
  registry:
    address: nacos://${nacos1.host}:${nacos1.port}/?username=${nacos1.username}&password=${nacos1.password},nacos://${nacos1.host}:${nacos1.port}/?username=${nacos1.username}&password=${nacos1.password},nacos://${nacos1.host}:${nacos1.port}/?username=${nacos1.username}&password=${nacos1.password}
    protocol: dubbo
    port: 20880

nacos:
  config:
    server-addr: ${nacos1.host}:${nacos1.port},${nacos2.host}:${nacos2.port},${nacos3.host}:${nacos3.port}

